# V -> verb

# r -> regular (add s at the end to make it multiple)
# i -> irregular (needs a lists of conjugations)

verb_list = [
    ["r", "wrap"],
    ["r", "iterate"],
    ["r", "loop"],
    ["r", "port"],
    ["r", "infect"],
    ["r", "append"],
    ["r", "change"],
    ["r", "normalize"],
    ["r", "average"],
    ["r", "decrypt"],
    ["r", "encrypt"],
    ["r", "convert"],
    ["r", "access"],
    ["r", "coordinate"],
    ["r", "power"],
    ["r", "monitor"],
    ["r", "regulate"],
    ["r", "detect"],
    ["r", "block"],
    ["r", "debug"],
    ["r", "observe"],
    ["r", "bypass"],
    ["r", "input"],
    ["r", "synthesize"],
    ["r", "connect"],
    ["r", "parse"],
    ["r", "generate"],
    ["r", "copy"],
    ["r", "analyze"],
    ["r", "control"],
    ["r", "benchmark"],
    ["r", "request"],
    ["r", "enter"],
    ["r", "call"],
    ["r", "detect"],
    ["r", "print"],
    ["r", "simulate"],
    ["r", "emulate"],
    ["r", "intercept"],
    ["r", "sequence"],
    ["r", "synchronize"],
    ["r", "test"],
    ["r", "tokenize"],
    ["r", "format"],
    ["r", "constrain"],
    ["r", "import"],
    ["r", "export"],
    ["r", "develop"],
    ["r", "invert"],
    ["r", "slice"],
    ["r", "index"],
    ["r", "join"],
    ["r", "shorten"],
    ["r", "partition"],
    ["r", "decompile"],
    ["r", "split"],
    ["r", "swap"],
    ["r", "cast"],
    ["r", "clear"],
    ["r", "stream"],
    ["r", "remove"],
    ["r", "add"],
    ["r", "signal"],
    ["r", "process"],
    ["r", "disconnect"],
    ["r", "start"],
    ["r", "interpret"],
    ["r", "yield"],
    ["r", "match"],
    ["r", "inspect"],
    ["r", "collect"],
    ["r", "restrict"],
    ["r", "display"],
    ["r", "address"],
    ["r", "identify"],
    ["i", "build", [["simple_present", {"i": "build", "you": "build", "it": "builds", "we": "build", "they": "build"}], ["simple_past", {"i": "built", "you": "built", "it": "built", "we": "built", "they": "built"}], ["simple_future", {"i": "will build", "you": "will build", "it": "will build", "we": "will build", "they": "will build"}]]],
    ["r", "load"],
    ["r", "define"],
    ["r", "decentralize"],
    ["r", "update"],
    ["r", "encode"],
    ["r", "virtualize"],
    ["r", "transmit"],
    ["r", "compile"],
    ["r", "randomize"],
    ["r", "deauth"],
    ["r", "alter"],
    ["r", "mute"],
    ["r", "hash"]
]


"""
- read
- write
- send
- override

- swap out
"""
